"""rename department

Revision ID: 5f9c58522b7c
Revises: 3767f9b78101
Create Date: 2024-03-17 05:11:11.474969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9c58522b7c'
down_revision = '3767f9b78101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments','department')
    # ### end Alembic commands ###
